CREATE TABLE orders (
    order_id VARCHAR(255) PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    additional_notes VARCHAR(255),
    mpesa_number INT,
    shipping_address VARCHAR(255) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    email_address VARCHAR(100),
    payment_method VARCHAR(50) NOT NULL,
    payment_result_id VARCHAR(255),
    payment_result_status VARCHAR(50),
    payment_result_update_time VARCHAR(50),
    payment_result_email_address VARCHAR(100),
    tax_price DECIMAL(10, 2) NOT NULL DEFAULT 0.0,
    shipping_price DECIMAL(10, 2) NOT NULL DEFAULT 0.0,
    total_price DECIMAL(10, 2) NOT NULL DEFAULT 0.0,
    is_paid BOOLEAN NOT NULL DEFAULT FALSE,
    paid_at DATETIME,
    is_delivered BOOLEAN NOT NULL DEFAULT FALSE,
    delivered_at DATETIME,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (user_id) REFERENCES users(id),
);
