
###
POST http://localhost:5000/category
Content-Type: application/json

{
    "category_name": "Milk 2",
    "category_image": "Milk is good for the sol",
    "category_description": "Milk is good for the sol",
    


    
}
